name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pyinstaller pynput
      - run: pyinstaller --onefile --windowed "macro.py"
      - uses: actions/upload-artifact@v4
        with:
          name: macro-exe
          path: dist/
